[build-system]
requires = ["flit_core>=3.4"]
build-backend = "flit_core.buildapi"

[project]
name = "api"
version = "0.1.0"
description = ""
python_requires = "3.12.0"
authors = [
    { name="Sunny Wan", email="Sunnywan2020@gmail.com" }
]
readme = "README.md"

